config/routes.rb
Grippy::Application.routes.draw do
  root "pages#home"
  
  get "pages/about"

  resources :charges

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
	end

	def create
	  # Amount in cents
	  @amount = 700

	  customer = Stripe::Customer.create(
	    :email => 'example@stripe.com',
	    :card  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Grippy',
	    :currency    => 'usd'
	  )

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to charges_path
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="700"></script>
<% end %>



<div class="col-md-offset-3 col-md-6">
	<div class="row">

		<div class="btn-group">
		  <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
		    Quantity: 1 <span class="caret"></span>
		  </button>
		  <ul class="dropdown-menu">
		    <li class="active"><a href="#">1</a></li>
		    <li><a href="#">2</a></li>
		    <li><a href="#">3</a></li>
		    <li><a href="#">4</a></li>
		    <li><a href="#">5</a></li>
		    <li><a href="#">6</a></li>
		    <li><a href="#">7</a></li>
		    <li><a href="#">8</a></li>
		    <li><a href="#">9</a></li>
		    <li><a href="#">10</a></li>
		  </ul>
		</div>

		<h3>Billing Information</h3>
		
	    <div class="row form-group">
	        <div class="col-sm-12">
	        	<label class="sr-only">Credit Card Number</label>

	            <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Credit Card Number" required="">
	        </div>
	    </div>

	    <div class="row form-group">
	        <div class="col-sm-6">
	        	<label class="sr-only">Expiration Date</label>
	            <input type="text" class="form-control" name="email" placeholder="Expiration Date" required="">
	        </div>
	        <div class="col-sm-6">
	        	<label class="sr-only">CVC</label>
	            <input type="email" class="form-control" name="phone" placeholder="Security Code" required="">
	        </div>
	    </div>
	    <div class="row form-group">
	        <div class="col-sm-6">
	        	<label class="sr-only">Billing Zipcode</label>
	            <input type="text" class="form-control" placeholder="Billing Zipcode" required="">
	        </div>
	        <div class="col-sm-6">
	        	<label class="sr-only">Contact Email</label>
	            <input type="Email" class="form-control" placeholder="Contact Email" required="">
	        </div>
	    </div> 



	</div><!-- row-->


	<div class="row">
		<h3>Shipping Address</h3>
	    <div class="row form-group">
	        <div class="col-sm-6">
	        	<label class="sr-only">First Name</label>
	            <input type="text" class="form-control" id="firstName" placeholder="First Name" required="">
	        </div>
	        <div class="col-sm-6">
	        	<label class="sr-only">Last Name</label>
	            <input type="text" class="form-control" id="middleName" placeholder="Last Name" required="">
	        </div>
	    </div>

	    <div class="row form-group">
	        <div class="col-sm-8">
	        	<label class="sr-only">Shipping Address</label>
	            <input type="email" class="form-control" placeholder="Shipping Address" required="">
	        </div>
	        <div class="col-sm-4">
	        	<label class="sr-only">Address 2</label>
	            <input type="email" class="form-control" placeholder="Apt, Unit, Suite" required="">
	        </div>
	    </div>
	    <div class="row form-group">
	        <div class="col-sm-4">
	        	<label class="sr-only">City</label>
	            <input type="text" class="form-control" placeholder="City" required="">
	        </div>
	        <div class="col-sm-4">
	        	<label class="sr-only">State</label>
	            <input type="text" class="form-control" placeholder="State" required="">
	        </div>
	        <div class="col-sm-4">
	        	<label class="sr-only">Zipcode</label>
	            <input type="text" class="form-control" placeholder="Zipcode" required="">
	        </div>
	    </div> 
		
		<div class="cc-submit well">
			<span><h4>Total (shipping included): </span><span><b>$7</b></h4></span>
			<%= link_to "Submit Order", "#", :class => 'btn btn-success btn-lg' %>
		</div>
		<span class="center text-muted">
			<i class="fa fa-lock"></i>
			Secured by 128-bit encryption
		</span>
	</div><!-- row-->


</div>

app/views/layouts/_header.html.erb
<div class="container">

<div class="header">
  <ul class="nav nav-pills pull-right">
    <li class="active"><%= link_to "Order Now", new_charge_path %></li>
    <li><a href="#">About</a></li>
    <li><a href="#">Contact</a></li>
  </ul>
  <h3 class="text-muted"><%= link_to "Grippy", root_path %></h3>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grippy</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<%= render 'layouts/header' %>

	<div class="container">
	<%= yield %>
	</div>

	<% flash.each do |name, msg| %>
	     <%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>

	<%= render 'layouts/footer' %>


</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<div class="hero-unit center">
<h1>Keeps your glasses on your face</h1>
<p class="lead">Stop having to push up your glasses when they slip down your nose. You look like a nerd.</p>
<%= link_to "Pre-order now for $7", new_charge_path, :class => 'btn btn-success btn-lg' %>

	<br><br>
	<img src="http://placehold.it/640x385">

</div>


<div class="row marketing center">
	<div class="col-md-3">
		<i class="fa fa-2x fa-medkit"></i>
		<h4>Hypoallergenic material</h4>
		<p>Made from the highest quality plastic, Grippys are hypoallergenic and won't irritate your skin from prolonged wear.</p>
	</div>

	<div class="col-md-3">
		<i class="fa fa-2x fa-clock-o"></i>
		<h4>Apply in Seconds</h4>
		<p>Just peel off the Grippy and stick it on your glasses frame. You'll be able to apply your Grippy in seconds.</p>
	</div>

	<div class="col-md-3">
		<i class="fa fa-2x fa-check-circle-o"></i>
		<h4>Won't damage your frames</h4>
		<p>Your Grippys won't leave any residue or marks on your frames. If you want to remove them, you just peel them off.</p>
	</div>

	<div class="col-md-3">
		<i class="fa fa-2x fa-smile-o"></i>
		<h4>Made in the USA</h4>
		<p>Grippys are manufactured with the highest quality standards in the US.</p>
	</div>
</div>

<div class="row">
	<h2 class="center">Included in the box</h2>
	<div class="col-md-offset-2 col-md-4">
		<h4>Grippy Grippy</h4>
		<p>h dshfjksd fkjsdhf kjshda fkahjsdfkhsadfkasdf</p>
	</div>
	<div class="col-md-4">
		<h4>GrippyGrippy</h4>
		<p>h dshfjksd fkjsdhf kjshda fkahjsdfkhsadfkasdf</p>
	</div>
</div>